[project]
name = 'Decentralized-Commercial-Plumbing-Maintenance'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.building-registration]
path = 'contracts/building-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.maintenance-scheduling]
path = 'contracts/maintenance-scheduling.clar'
clarity_version = 2
epoch = 2.5

[contracts.system-inventory]
path = 'contracts/system-inventory.clar'
clarity_version = 2
epoch = 2.5

[contracts.water-usage]
path = 'contracts/water-usage.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
